def test_start_creates_kernel():
    ...

def test_double_start_raises():
    ...

def test_shutdown_without_start_raises():
    ...

def test_shutdown_clears_kernel():
    ...

def test_kernel_property_before_start_raises():
    ...